name: filedroid
description: Android file transfer for macOS via ADB.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  macos_ui: ^2.0.9
  provider: ^6.1.1
  path: ^1.9.0
  intl: ^0.20.2
  file_picker: ^10.3.10
  desktop_drop: ^0.7.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  fake_async: ^1.3.3
  plugin_platform_interface: ^2.1.8
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true
